# Generated by Django 4.0.2 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
