# Generated by Django 4.0.2 on 2022-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_userdetail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
    ]
