# Generated by Django 4.0.2 on 2022-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_remove_userdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default='user-profile.png', null=True, upload_to='user'),
        ),
    ]
