# Generated by Django 4.0.2 on 2022-03-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Seller.product'),
        ),
    ]
