# Generated by Django 4.0.2 on 2022-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_bid_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
    ]
