# Generated by Django 4.0.2 on 2022-04-15 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_orders_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
