# Generated by Django 4.0.2 on 2022-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_orders_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
    ]
