# Generated by Django 4.0.2 on 2022-04-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0011_paytmhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user',
        ),
    ]
