# Generated by Django 4.0.2 on 2022-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_remove_paytmhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(default='', max_length=12),
        ),
    ]
