# Generated by Django 4.0.2 on 2022-04-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0016_remove_sellerdetail_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetail',
            name='photo',
            field=models.ImageField(default='user-profile.png', null=True, upload_to='user'),
        ),
    ]
