# Generated by Django 4.0.2 on 2022-04-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0017_alter_sellerdetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
